package com.johnverz;

import java.util.List;
import java.util.Scanner;

import com.johnverz.model.Task;
import com.johnverz.service.NetworkService;

public class Main {
    public static void main(String[] args) {
        String host = "jsonplaceholder.typicode.com"; // domain name
        int port = 80;
        String path = "/todos";

        NetworkService ns = new NetworkService(host, port);

        Task task = ns.fetch(path, 1);
        System.out.println("Single Task, id 1");
        System.out.println(task);
        System.out.println("All tasks");

        List<Task> tasks = ns.fetchAll(path);
        tasks.forEach((t) -> {
            System.out.println(t);
        });

        System.out.println("\n--- Creating a New Task ---");
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter task title: ");
        String title = scanner.nextLine();

        // Hardcode userId to 1, assign a dummy id (typically generated by server), and
        // mark as not completed
        Task newTask = new Task(1, 201, title, false);

        boolean success = ns.send(path, newTask);
        if (success) {
            System.out.println("Task created successfully!");
        } else {
            System.out.println("Failed to create task.");
        }

        scanner.close();

    }
}